services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web-mvc
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/conf-available/servername.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    command: /bin/bash -c "ln -s /etc/apache2/conf-available/servername.conf /etc/apache2/conf-enabled/servername.conf && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db-mvc
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-mvc
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mvc
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3000:80"
    depends_on:
      - db

volumes:
  db_data: